// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfxuktnsecfbxmvuyoqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmeHVrdG5zZWNmYnhtdnV5b3F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NzE3MjYsImV4cCI6MjA2MDM0NzcyNn0.NmGBJRPRHZxktvI4-Xi3JjIvInHZQqP3zyfXmA_pwG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);